// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"TikTokLite/app/message/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.MessageMiddleWare},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/chat",
					Handler: messageChatHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/action",
					Handler: messageActionHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/douyin/message"),
	)
}
