// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id               int64  `json:"id"`
	Username         string `json:"username"`
	Follow_count     int64  `json:"follow_count"`
	Follower_count   int64  `json:"follower_count"`
	Is_follow        bool   `json:"is_follow"`
	Avatar           string `json:"avatar"`
	Background_image string `json:"background_image"`
	Signature        string `json:"signature"`
	Total_favorited  int64  `json:"total_favorited"`
	Work_count       int64  `json:"work_count"`
	Favorite_count   int64  `json:"favorite_count"`
}

type Video struct {
	Id             int64  `json:"id"`
	Author         User   `json:"author"`
	Play_url       string `json:"play_url"`
	Cover_url      string `json:"cover_url"`
	Favorite_count int64  `json:"favorite_count"`
	Comment_count  int64  `json:"comment_count"`
	Is_Favorite    bool   `json:"is_favorite"`
	Title          string `json:"title"`
}

type PublishVideoReq struct {
	Title string `json:"title"`
}

type PublishVideoResp struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}
