// Code generated by goctl. DO NOT EDIT.
// Source: message.proto

package server

import (
	"context"

	"TikTokLite/app/message/cmd/rpc/internal/logic"
	"TikTokLite/app/message/cmd/rpc/internal/svc"
	"TikTokLite/app/message/cmd/rpc/pb"
)

type MessageServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMessageServer
}

func NewMessageServer(svcCtx *svc.ServiceContext) *MessageServer {
	return &MessageServer{
		svcCtx: svcCtx,
	}
}

func (s *MessageServer) Chat(ctx context.Context, in *pb.DouyinMessageChatRequest) (*pb.DouyinMessageChatResponse, error) {
	l := logic.NewChatLogic(ctx, s.svcCtx)
	return l.Chat(in)
}

func (s *MessageServer) Action(ctx context.Context, in *pb.DouyinMessageActionRequest) (*pb.DouyinMessageActionResponse, error) {
	l := logic.NewActionLogic(ctx, s.svcCtx)
	return l.Action(in)
}
