// Code generated by goctl. DO NOT EDIT.
package types

type Message struct {
	Id         int64 `json:"id"`
	ToUserId   int64 `json:"to_user_id"`
	FromUserId int64 `json:"from_user_id"`
	Content    int64 `json:"content"`
	CreateTime int64 `json:"create_time"`
}

type DouyinMessageChatRequestt struct {
	Token      string `json:"token"`
	ToUserId   int64  `json:"to_user_id"`
	PreMsgTime int64  `json:"pre_msg_time"` // 上次最新消息的时间
}

type DouyinMessageChatResponse struct {
	StatusCode  int32     `json:"status_code"` // 0-成功, 其他-失败
	StatusMsg   int32     `json:"status_msg"`
	MessageList []Message `json:"message_list"`
}

type DouyinMessageActionRequest struct {
	Token      string `json:"token"`
	ToUserId   int64  `json:"to_user_id"`
	ActionType int32  `json:"action_type"` // 1-发送消息
	Content    string `json:"content"`
}

type DouyinMessageActionResponse struct {
	StatusCode int32 `json:"status_code"`
	StatusMsg  int32 `json:"status_msg"`
}
